# Generated by Django 2.0.1 on 2019-08-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190818_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
