# Generated by Django 2.0.1 on 2019-08-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190819_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.TextField(),
        ),
    ]
