# Generated by Django 2.0.1 on 2019-08-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190819_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
