# Generated by Django 2.0.1 on 2019-08-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190819_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tech',
        ),
        migrations.AddField(
            model_name='post',
            name='technologies',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
